# Generated by Django 3.1.2 on 2021-06-28 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0004_auto_20210628_0345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientcase',
            name='case_type',
            field=models.CharField(choices=[('ГР', 'Гражданское'), ('УГ', 'Уголовное')], max_length=300, verbose_name='Тип дела'),
        ),
        migrations.AlterField(
            model_name='clientcase',
            name='service_type',
            field=models.CharField(choices=[('К', 'Консультация'), ('У', 'Учасите')], max_length=300, verbose_name='Тип услуг'),
        ),
    ]
